export default{
  data:{
    GetOpenidByCode:'/Data/GetOpenidByCode',
    GetUInfoByOpenId:'/Data/GetUserInfoByOpenId',
    UpdateUserInfoHome:'/Data/UpdateUserInfoHome',
    GetBanners:'/Data/GetBanners',
    GetDoors:'/Data/GetDoors',
    GetTeacherDoors:'/Data/GetTeacherDoors',
    GetDoorsById:'/Data/GetDoorsById'
  },
  cardTemplate:{
    GetTemplates:'/Data/GetCardTempalte',
    GetCardTemplateById:'/Data/GetCardTemplateById',
    CreateCardTempalte:'/Data/CreateCardTempalte',
    UpdateCardtemplate:'/Data/UpdateCardtemplate',
  },
  Subject:{
    GetSubjects:'/Data/GetSubjects',
    CreateSubject:'/Data/CreateSubject',
    GetSubjectById:'/Data/GetSubjectById',
    UpdateSubject:'/Data/UpdateSubject',
    GetDoorInfo:'/Data/GetDoorInfo',
  },
  process:{
    UploadFile:'/Home/UploadFile',
    MvcUploadFile:'/Homemvc/UploadFile',
    CreateDoors:'/Data/CreateDoors',
    UpdateDoors:'/Data/UpdateDoors',
    UpdateUInfoSetting:'/Data/UpdateUserInfoSetting'
  },
  Lessons:{
    GetDoorInfo:'/Data/GetDoorInfo'
  }
}